Synchronize ci.yml and release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,4 +1,3 @@
-# https://github.com/dart-lang/setup-dart/blob/main/README.md
 name: Release
 
 on:
@@ -8,15 +7,18 @@ on:
 
 env:
   BUILD_VERSION: "${{ github.ref }}"
-  BUILD_NUMBER: "${{ github.run_number }}"
 
 jobs:
-  build-binaries:
-    name: "Build binaries"
-    runs-on: ${{ matrix.os }}
+  build-binaries-macos-amd64:
+    name: "Build binaries for macOS AMD64"
+    runs-on: "${{ matrix.os }}"
     strategy:
       matrix:
-        os: [ubuntu-latest, macos-latest]
+        os: [macos-latest]
+        arch: [amd64]
+    env:
+      BUILD_OS: "macos"
+      BUILD_ARCH: "${{ matrix.arch }}"
     steps:
       - uses: actions/checkout@v3
       - uses: dart-lang/setup-dart@v1.3
@@ -26,14 +28,46 @@ jobs:
       - name: Install dependencies
         run: dart pub get
 
-      - name: Set BUILD_OS environment variable for Linux
-        if: ${{ matrix.os == 'ubuntu-latest' }}
-        run: echo "BUILD_OS=linux" >> $GITHUB_ENV
-      - name: Set BUILD_OS environment variable for macOS
-        if: ${{ matrix.os == 'macos-latest' }}
-        run: echo "BUILD_OS=darwin" >> $GITHUB_ENV
-      - name: Set BUILD_ARCH environment variable
-        run: echo "BUILD_ARCH=amd64" >> $GITHUB_ENV
+      - name: Create build folder
+        run: mkdir -p build
+
+      - name: Build git-lfs-authenticate
+        run: dart compile exe bin/git_lfs_authenticate.dart --output build/git-lfs-authenticate
+      - uses: actions/upload-artifact@v3
+        with:
+          name: git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_VERSION }}
+          path: build/git-lfs-authenticate
+
+      - name: Build git-lfs-server
+        run: dart compile exe bin/git_lfs_server.dart --output build/git-lfs-server
+      - uses: actions/upload-artifact@v3
+        with:
+          name: git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_VERSION }}
+          path: build/git-lfs-server
+
+  build-binaries-linux-amd64:
+    name: "Build binaries for Linux AMD64"
+    runs-on: "${{ matrix.os }}"
+    strategy:
+      matrix:
+        os: [ubuntu-latest]
+        arch: [amd64]
+    container:
+      image:
+        amd64/dart
+      options: --tty --platform linux/${{ matrix.arch }}
+    env:
+      BUILD_OS: "linux"
+      BUILD_ARCH: "${{ matrix.arch }}"
+    steps:
+      - uses: actions/checkout@v3
+      - uses: dart-lang/setup-dart@v1.3
+        with:
+          sdk: stable
+          architecture: x64
+
+      - name: Install dependencies
+        run: dart pub get
 
       - name: Create build folder
         run: mkdir -p build
@@ -42,34 +76,97 @@ jobs:
         run: dart compile exe bin/git_lfs_authenticate.dart --output build/git-lfs-authenticate
       - uses: actions/upload-artifact@v3
         with:
-          name: git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.BUILD_VERSION }}
+          name: git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_VERSION }}
           path: build/git-lfs-authenticate
 
       - name: Build git-lfs-server
         run: dart compile exe bin/git_lfs_server.dart --output build/git-lfs-server
       - uses: actions/upload-artifact@v3
         with:
-          name: git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.BUILD_VERSION }}
+          name: git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_VERSION }}
+          path: build/git-lfs-server
+
+  build-binaries-linux-arm64:
+    name: "Build binaries for Linux ARM64"
+    runs-on: "${{ matrix.os }}"
+    strategy:
+      matrix:
+        os: [ubuntu-latest]
+        arch: [arm64]
+    env:
+      BUILD_OS: "linux"
+      BUILD_ARCH: "${{ matrix.arch }}"
+    steps:
+      - uses: actions/checkout@v3
+      - uses: uraimo/run-on-arch-action@v2
+        name: Build ARM64 binaries
+        with:
+          arch: aarch64
+          distro: ubuntu18.04
+          setup: |
+            mkdir -p "${PWD}/build"
+          dockerRunArgs: |
+            --volume "${PWD}/build:/build"
+          env: |
+            BUILD_BRANCH: "${{ github.head_ref }}"
+          install: |
+            apt-get update -q
+            apt-get install -q -y curl git unzip
+            curl --connect-timeout 15 --retry 5 "https://storage.googleapis.com/dart-archive/channels/be/raw/latest/sdk/dartsdk-linux-arm64-release.zip" > "${HOME}/dartsdk.zip"
+            unzip -o "${HOME}/dartsdk.zip" -d "${HOME}" > /dev/null
+            if [ $? -ne 0 ]; then
+              echo -e "::error::Download failed! Please check passed arguments."
+              exit 1
+            fi
+            rm "${HOME}/dartsdk.zip"
+            PUBCACHE="${HOME}/.pub-cache"
+            DART_HOME="${HOME}/dart-sdk"
+            echo "PUB_CACHE=${PUBCACHE}" >> ${HOME}/.bashrc
+            echo "Pub cache set to: ${PUBCACHE}"
+            echo "DART_HOME=${DART_HOME}" >> ${HOME}/.bashrc
+            echo -e "Successfully installed Dart SDK:"
+            ${HOME}/dart-sdk/bin/dart --version
+          run: |
+            git clone --quiet https://github.com/khoa-io/git-lfs-server.git --branch "${BUILD_BRANCH}" --depth 1
+            cd git-lfs-server
+            "${HOME}/dart-sdk/bin/dart" pub get
+            "${HOME}/dart-sdk/bin/dart" compile exe bin/git_lfs_server.dart --output git-lfs-server
+            "${HOME}/dart-sdk/bin/dart" compile exe bin/git_lfs_authenticate.dart --output git-lfs-authenticate
+            cp git-lfs-server "/build"
+            cp git-lfs-authenticate "/build"
+      - uses: actions/upload-artifact@v3
+        with:
+          name: git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_VERSION }}
+          path: build/git-lfs-authenticate
+      - uses: actions/upload-artifact@v3
+        with:
+          name: git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_VERSION }}
           path: build/git-lfs-server
 
   build-images:
     name: "Build images"
     needs:
-      - build-binaries
+      - build-binaries-linux-amd64
+      - build-binaries-linux-arm64
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        arch: [amd64, arm64]
+    env:
+      BUILD_OS: "linux"
+      BUILD_ARCH: "${{ matrix.arch }}"
+    permissions:
+      contents: read
+      packages: write
     steps:
-      - name: Set BUILD_OS environment variable for Linux
-        run: echo "BUILD_OS=linux" >> $GITHUB_ENV
-      - name: Set BUILD_ARCH environment variable
-        run: echo "BUILD_ARCH=amd64" >> $GITHUB_ENV
       - uses: actions/checkout@v3
       - uses: actions/download-artifact@v3
         with:
-          name: git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.BUILD_VERSION }}
+          name: git-lfs-authenticate-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_VERSION }}
           path: build/git-lfs-authenticate
       - uses: actions/download-artifact@v3
         with:
-          name: git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_NUMBER }}-${{ env.BUILD_VERSION }}
+          name: git-lfs-server-${{ env.BUILD_OS }}-${{ env.BUILD_ARCH }}-${{ env.BUILD_VERSION }}
           path: build/git-lfs-server
       - name: List binaries
         run: ls -la build
@@ -78,19 +175,22 @@ jobs:
         uses: docker/setup-qemu-action@v2
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
-      - name: Login to Docker Hub
+      - name: Login to GitHub Packages
         uses: docker/login-action@v1
         with:
-          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
       - name: Build and push Docker images
         uses: docker/build-push-action@v3
         with:
           context: .
           file: ./Dockerfile
-          platforms: linux/amd64,linux/arm64
+          platforms: linux/${{ matrix.arch }}
           push: true
-          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/amz-git-mirroring:${{ env.BUILD_VERSION }}
+          tags: |
+            ${{ secrets.DOCKER_HUB_USERNAME }}/amz-git-mirroring:${{ env.BUILD_VERSION }}
+            ${{ secrets.DOCKER_HUB_USERNAME }}/amz-git-mirroring:latest
       - name: Update repo description
         uses: peter-evans/dockerhub-description@v2
         with:
